inherit_from:
  - .rubocop_todo.yml

plugins:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec # If using RSpec


AllCops:
  TargetRubyVersion: 3.1 # Change based on your Ruby version
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "db/**/*"
    - "node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"

Rails:
  Enabled: true

Performance/Detect:
  Enabled: true

Performance/RedundantMerge:
  Enabled: true

Performance/ReverseEach:
  Enabled: true
